watch_stylesheet: true
watch_config: true

komorebi:
  start_command: "pwsh -Command komorebic start --ahk"
  stop_command: "komorebic stop"
  reload_command: "pwsh -Command komorebic stop && komorebic start --ahk"

bars:
  status-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    blur_effect:
      enabled: true 
      acrylic: true 
      dark_mode: false
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 40
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:
        [
          "search_button",
          "komorebi_workspaces", 
        ]
      center: ["clock"]

widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      max_length: 56
      label_icon: true
      label_icon_size: 16
      max_length_ellipsis: ".."
      monitor_exclusive: false

  clock:
      type: "yasb.clock.ClockWidget"
      options:
        label: "{%a %I:%M %p}"
        label_alt: "{%A %d %B %Y %I:%M %p}"
        #timezones: ["Europe/London", "America/New_York"]
        timezones: []
        callbacks:
          on_middle: "exec explorer.exe shell:Appsfolder\\Microsoft.WindowsAlarms_8wekyb3d8bbwe!App"
          on_right: "next_timezone"


  komorebi_workspaces:
      type: "komorebi.workspaces.WorkspaceWidget"
      options:
        label_offline: "Komorebi Offline"
        label_workspace_btn: "\uf4c3"
        label_default_name: "{index}"
        label_zero_index: false
        hide_empty_workspaces: false

  search_button:
      type: "yasb.custom.CustomWidget"
      options:
        label: "\uf0e7"
        label_alt: "<span>\uf422</span> Search"
        class_name: "search-widget"
        exec_options:
          run_once: true
        callbacks:
          on_left: "do_nothing"
          on_right: "do_nothing"
